# Generated by Django 4.1.1 on 2022-09-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='content',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='word',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='owner_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
