# Generated by Django 4.1.1 on 2022-10-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_content_word_count_word_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='content',
            field=models.CharField(default='empty', max_length=30, unique=True),
        ),
    ]
